### ISSUE TITLE
Update to 6.0.45-14358-1

### ISSUE THREAD

**Issue by ThyMYthOS** [hairychris/unifi-snap#1]
Please update to the latest version.

**Comment by hairychris** [comment]
The build is now failing with:

```
Failed to copy '/build/unifi/parts/unifi/build/etc/init.d/unifi': it's a symlink pointing outside the snap.
```

Looks like it should be a fairly simple fix.

**Comment by hairychris** [comment]
Looks like https://github.com/hairychris/unifi-snap/commit/9d62f16094c34a0c6fe8a5371e0c02500513927c fixed it.
